name: CI
on:
  push:
  pull_request:
    types: [ opened ]

jobs:
  ci:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install
      - name: Testing
        run: yarn test:unit
